<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Authors>David Liebeherr</Authors>
		<Company>rent-a-developer</Company>
		<Copyright>Copyright © rent-a-developer / David Liebeherr</Copyright>
		<TargetFramework>net8.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<TieredCompilation>true</TieredCompilation>
		<RepositoryUrl>https://github.com/rent-a-developer/ArgumentNullGuards.git</RepositoryUrl>
		<RepositoryType>GIT</RepositoryType>
		<Description>A simple .NET library that verifies constructors and methods have guards in place against null arguments.</Description>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<IncludeSymbols>true</IncludeSymbols>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
		<EnableNETAnalyzers>True</EnableNETAnalyzers>
		<AnalysisLevel>latest-all</AnalysisLevel>
		<TieredCompilation>true</TieredCompilation>
		<TieredPGO>true</TieredPGO>
		<RootNamespace>RentADeveloper.ArgumentNullGuards</RootNamespace>
		<AssemblyTitle>rent-a-developer ArgumentNullGuards</AssemblyTitle>
		<AssemblyName>RentADeveloper.ArgumentNullGuards</AssemblyName>
		<DocumentationFile>RentADeveloper.ArgumentNullGuards.xml</DocumentationFile>
		<Version>2.0.0</Version>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<PackageId>ArgumentNullGuards</PackageId>
		<PackageLicenseFile>LICENSE.md</PackageLicenseFile>
		<PackageProjectUrl>https://github.com/rent-a-developer/ArgumentNullGuards</PackageProjectUrl>
		<PackageIcon>Resources\icon.png</PackageIcon>
		<PackageTags>null argument parameter method constructor C# .net ArgumentNullException test verify</PackageTags>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<PackageReleaseNotes>See CHANGELOG.md.</PackageReleaseNotes>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\CHANGELOG.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\..\LICENSE.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Update="Resources\icon.png">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ErrorProne.NET.CoreAnalyzers" Version="0.1.2">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
